-- DEPRECATED: shared org-chart state no longer uses Supabase.
-- The app now persists via Vercel Blob through /api/org-chart.
--
-- Setup:
--   1. Vercel Dashboard → Storage → Create Blob store → connect this project
--   2. Redeploy (BLOB_READ_WRITE_TOKEN is injected automatically)
--
-- Until Blob is connected, the app runs in local-only mode (browser localStorage)
-- and JSON Import/Export still works for manual sharing.

-- Legacy schema kept for reference only:
-- create table if not exists public.org_chart_state (
--   id text primary key default 'default',
--   payload jsonb not null,
--   updated_at timestamptz not null default now()
-- );
